# Generated by Django 6.0.5 on 2026-07-01 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_add_soft_delete_to_course"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "student"},
                related_name="enrolled_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
