# Generated by Django 6.0.5 on 2026-06-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the quiz becomes available. Null = immediately.",
                null=True,
            ),
        ),
    ]
