# Generated by Django 6.0.5 on 2026-07-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design_studio", "0002_alter_designsubmission_status_designfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="designproject",
            name="thumbnail_url",
            field=models.URLField(blank=True),
        ),
    ]
