# Generated by Django 6.0.5 on 2026-06-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ide", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lab",
            name="is_embed",
            field=models.BooleanField(default=False),
        ),
    ]
